config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :groups do
    resources :bills
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'splash#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :group
  validates :name, presence: true
  validates :amount, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :bills, dependent: :destroy
  belongs_to :user

  validates :name, presence: true
  validates :icon, presence: true

  def icons
    JSON.parse(File.read('./app/icons/icons.json'))
  end
end

app/models/group_bill.rb
class GroupBill < ApplicationRecord
  belongs_to :group
  belongs_to :bill
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bills, foreign_key: 'author_id'
  has_many :groups, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name])
  end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_bill, only: %i[show edit update destroy]

  # GET /bills or /bills.json
  def index
    @group = current_user.groups.find(params[:group_id])
    @bills = @group.bills
  end

  # GET /bills/1 or /bills/1.json
  def show; end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit; end

  # POST /bills or /bills.json
  def create
    @bill = Bill.new(bill_params)

    respond_to do |format|
      if @bill.save
        format.html { redirect_to group_bills_path, notice: 'Bill was successfully created.' }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1 or /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to bill_url(@bill), notice: 'Bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1 or /bills/1.json
  def destroy
    @bill.destroy

    respond_to do |format|
      format.html { redirect_to bills_url, notice: 'Bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_bill
    @bill = Bill.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def bill_params
    params.require(:bill).permit(:name, :amount, :author_id, :group_id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # before_action :set_group, only: %i[show edit update destroy]
  before_action :authenticate_user!
  # GET /groups or /groups.json
  def index
    @groups = Group.where(user_id: current_user.id)
  end

  # GET /groups/1 or /groups/1.json
  def show
    @group = Group.find(params[:id])
    @bills = @group.bills.all
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @group = current_user.groups.create(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_path, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon, :user_id)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    redirect_to groups_path if user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/group_bills_helper.rb
module GroupBillsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/views/bills/_bill.html.erb
<div class="container-fluid">
<div class="bills">


 <% @bills.order('id DESC').each do |bill| %>
 
     <div class="mb-3">
      <div class="container-flud mx-2 px-2 bg-white border-bottom">
        <p class="pt-2"><%= bill.name %></p>
        <p class="pb-1 mb-0">Transactionº<%= bill.created_at.to_time.to_i %></p>
        <span class="fa fa-calendar"></span> <span class="mx-1"><%= bill.created_at %></span>
      </div>
      <div class="container-flud mx-2 px-2 bg-white border-bottom">
        <p class="py-2 m-0 d-flex justify-content-between">
        <strong>Payment:</strong>
        $<%= bill.amount %>
        </p>
      </div>
      </div>
      <% end %>
  

</div>
</div>

app/views/bills/_form.html.erb
<%= form_with(model: bill, url: group_bills_path) do |form| %>
  <% if bill.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
        <% bill.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :name, class: 'form-control my-3', placeholder: 'Enter name' %>
  </div>

  <div class="form-group">
    <%= form.text_field :amount, class: 'form-control my-3', placeholder: 'Enter amount' %>
    <%= form.hidden_field :group_id, {value: params[:group_id]} %>
    <%= form.hidden_field :author_id, {value: current_user.id} %>
  </div>


  <div class="form-group">
    <%= form.submit 'Save Bill', class: 'btn btn-primary btn-sm bg-blue col-12' %>
  </div>
<% end %>

app/views/bills/_group.html.erb
<div class="container-fluid">
  <%= link_to group_path(group.id) do %>
  <div class="row d-flex mb-3 bg-white py-1 mx-1 box-card">
     <div class="row-25">
       <img src=<%= group.icon %> alt=<%= group.name %> class="img-fluid img-thumbnail border-0" />
     </div>
     <div class="row-75 px-0 d-flex justify-content-between">
      <div>
       <p class="mb-0 mt-2"><%= group.name %></p>
       <p><%= Date.parse(group.created_at.to_s, '%m-%d-%Y') %></p>
      </div>
      <div class="px-3">
        <strong>$<%= group.bills.inject(0){ |sum, bill| sum + bill.amount.to_i } %></strong>
      </div>
     </div>
  </div>
  <% end %>
</div>

app/views/bills/edit.html.erb
<h1>Editing bill</h1>

<%= render "form", bill: @bill %>

<br>

<div>
  <%= link_to "Show this bill", @bill %> |
  <%= link_to "Back to bills", bills_path %>
</div>

app/views/bills/index.html.erb
<h1 class="bg-primary w-100 position-fixed top-0 ">TRANSACTIONS</h1>
<%= render @group%>
<div id="bills">

    <%= render "bill" %>
   
</div>


<div class="bg-green p-3 w-100 position-fixed bottom-0">

 <%= link_to "go back to categories", groups_path, class: 'btn  fw-bold col-12 text-uppercase' %> 


  <%= link_to "Add a New transaction", new_group_bill_path(@group.id), class: 'btn bg-green fw-bold col-12 text-uppercase' %>
</div>

app/views/bills/new.html.erb
<h1 class="bg-primary w-100 position-fixed top-0 ">NEW TRANSACTION</h1>
<div class="container-fluid">
  <div class="row">
    <%= render "form", bill: @bill, group_id: @group_id %>
  </div>
</div>

app/views/bills/show.html.erb
<h1 class="bg-green p-3 w-100 position-fixed top-0 mb-5">CATEGORIES</h1>
<%= render @bill %>

<div>
  <%= link_to "Edit this bill", edit_bill_path(@bill) %> |
  <%= link_to "Back to bills", bills_path %>

  <%= button_to "Destroy this bill", @bill, method: :delete %>
</div>

app/views/group_bills/_form.html.erb
<%= form_with(model: group_bill) do |form| %>
  <% if group_bill.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group_bill.errors.count, "error") %> prohibited this group_bill from being saved:</h2>

      <ul>
        <% group_bill.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div>
    <%= form.label :group_id, style: "display: block" %>
    <%= form.text_field :group_id %>
  </div>

  <div>
    <%= form.label :bill_id, style: "display: block" %>
    <%= form.text_field :bill_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/group_bills/_group_bill.html.erb
<div id="<%= dom_id group_bill %>">
</div>

app/views/group_bills/edit.html.erb
<h1>Editing group bill</h1>

<%= render "form", group_bill: @group_bill %>

<br>

<div>
  <%= link_to "Show this group bill", @group_bill %> |
  <%= link_to "Back to group bills", group_bills_path %>
</div>

app/views/group_bills/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Group bills</h1>

<div id="group_bills">
  <% @group_bills.each do |group_bill| %>
    <%= render group_bill %>
    <p>
      <%= link_to "Show this group bill", group_bill %>
    </p>
  <% end %>
</div>

<%= link_to "New group bill", new_group_bill_path %>

app/views/group_bills/new.html.erb
<h1>New group bill</h1>

<%= render "form", group_bill: @group_bill %>

<br>

<div>
  <%= link_to "Back to group bills", group_bills_path %>
</div>

app/views/group_bills/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @group_bill %>

<div>
  <%= link_to "Edit this group bill", edit_group_bill_path(@group_bill) %> |
  <%= link_to "Back to group bills", group_bills_path %>

  <%= button_to "Destroy this group bill", @group_bill, method: :delete %>
</div>

app/views/groups/_form.html.erb
<div class="container mt-3">
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: 'form-control', placeholder: 'Enter name' %>
  </div>


  <%
=begin%>
 <div>
    <%= form.label :icon, style: "display: block" %>
    <%= form.text_field :icon, class: 'form-control', placeholder: 'Enter name' %>
  </div> 
<%
=end%>
<div class="select-field">
   <%= form.select :icon, @group.icons.map { |icon| [icon['name'], icon['url']] },
   { :include_blank => 'Choose category icon' }, :required => true, class:'select-icon' %>
  </div>
  <div>
    <%= form.submit "Save Category", class: 'btn btn-sm bg-blue col-12 mt-3' %>
  </div>
<% end %>
</div>

app/views/groups/_group.html.erb
<div class="container-fluid">
  <%= link_to group_path(group.id) do %>
  <div class="row d-flex mb-3 bg-white py-1 mx-1 box-card">
     <div class="row-25">
       <img src=<%= group.icon %> alt=<%= group.name %> class="img-fluid img-thumbnail border-0" />
     </div>
     <div class="row-75 px-0 d-flex justify-content-between">
      <div>
       <p class="mb-0 mt-2"><%= group.name %></p>
       <p><%= Date.parse(group.created_at.to_s, '%m-%d-%Y') %></p>
      </div>
      <div class="px-3">
        <strong>$<%= group.bills.inject(0){ |sum, bill| sum + bill.amount.to_i } %></strong>
      </div>
     </div>
  </div>
  <% end %>
</div>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
<p style="color: green"><%= notice %></p>
<h1 class="bg-primary w-100 position-fixed top-0 ">CATEGORIES</h1>
<div id="groups">
  <% @groups.each do |group| %>
      <%= render group %>
    <% end %>
</div>
 <div class="bg-green p-3 w-100 position-fixed bottom-0">
  <%= link_to "Add a New category", new_group_path, class: 'btn bg-green fw-bold col-12 text-uppercase' %>
</div> 

app/views/groups/new.html.erb
<h1 class="bg-primary  w-100 position-fixed top-0 "> NEW CATEGORIES</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Back to categories", groups_path, class: 'btn btn-sm col-12' %>
</div>

app/views/groups/show.html.erb
<p style="color: green"><%= notice %></p>
<h1 class="bg-primary w-100 position-fixed top-0 ">TRANSACTIONS</h1>
<%= render @group%>
<%
=begin%>
 <div class="px-3 d-flex justify-content-end mb-3">
  Total: $<%= @group.bills.inject(0){ |sum, bill| sum + bill.amount.to_i } %>
</div> 
<%
=end%>

 <%= render @bills %> 


<div class="bg-green p-3 w-100 position-fixed bottom-0">
<%= link_to "go back to categories", groups_path, class: 'btn  fw-bold col-12 text-uppercase' %> 
  <%= link_to "Add a New transaction", new_group_bill_path(@group.id), class: 'btn bg-green fw-bold col-12 text-uppercase' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetAp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <%= stylesheet_link_tag "application" %>

    <script src="https://kit.fontawesome.com/46794738cc.js" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
        <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/splash/index.html.erb
<div class="container">
  <h1 >Budget App</h1>

  <div class="row d-flex flex-column mt-5">
  
      <div class="mt-5">
       <%= link_to 'Sign In', new_user_session_path, class: 'btn btn-primary bg-blue btn-sm col-12' %>
      </div>
      <div class="mt-3">
      <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary bg-blue btn-sm col-12' %>
     </div>
  </div>

</div>